name: C/C++ CI

on:
  push:
    branches:
      - master
      - dev
      - ci
      - oskar
      - michal
      - bartek
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Configure CMake
        run: cmake -B build
        working-directory: src

      - name: Build All Targets
        run: cmake --build build
        working-directory: src

      - name: Run unit tests via CTest
        working-directory: src/build
        run: ctest --output-on-failure
