name: Auto Clang Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Umożliwia push zmian

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Run clang-format
        run: |
          find . -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file -i

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply clang-format fixes"
          git push
