name: Clang-Tidy Check

on: [push]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: cmake
        run: cmake .
      - name: make all targets
        run: make all

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cmake ninja-build

      - name: Configure CMake
        run: |
          cmake -S ./src -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja

      - name: Run Clang-Tidy
        run: clang-tidy -p build $(find . -name '*.cpp' -or -name '*.h')