name: Cppcheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt install cppcheck -y

      - name: Find C++ Standard Library Path
        run: echo "CXX_INCLUDE_PATH=$(g++ -print-file-name=include | sed 's|/c++||')" >> $GITHUB_ENV

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 -I${{ env.CXX_INCLUDE_PATH }} \
          --suppress=missingInclude --suppress=missingIncludeSystem \
          src/UE/Application src/UE/main.cpp 2> >(tee cppcheck.log)
          [ ! -s cppcheck.log ]
